### ISSUE TITLE
Compatibility with Tidy5e

### ISSUE THREAD

**Issue by DarKDinDoN** [Sepichat/FoundryVTT-GiveItem#1]
Hello,

On Tidy5e, you can right-click on an item to get a context menu. In this context menu the icon is showing up but no label.

**Comment by Sepichat** [comment]
I didn't try Tidy5e Character Sheets yet, so I was not aware there was a difference.
I will check how to make this module compatible with Tidy5e.
Thanks for the suggestion.

**Comment by Sepichat** [comment]
I just ran some tests and it seems like the mod actually works with Tidy5e.
It's not perfect, I could add a label to the trading icon, when you right click an item to offer it, but it will still work.
I will see how I can improve it a bit but you should be able to use it already.

**Comment by Sepichat** [comment]
Update is done in 1.6.0.
The button appears after Edit item with a proper label (Give item)
