### ISSUE TITLE
Update to v0.8.x

### ISSUE THREAD

**Issue by GabrielOsvair** [Sepichat/FoundryVTT-GiveItem#12]
Helo! I really like this module and would like to know if it will be updated.

**Comment by Sepichat** [comment]
Hello,

I will probably take the time to migrate it to the version 0.8.x
I didn't notice that it was already stable.
I will try to work on that asap.

**Comment by TheBird956** [comment]
@Sepichat any updates on this?

The linked pull request seems pretty simple. I'll try to test it later today.

**Comment by Sepichat** [comment]
Hello guys,

Someone provided a fix for that compatibility issue that I just merged.
You can check #13
