### ISSUE TITLE
Incompatible with v0.8.8

### ISSUE THREAD

**Issue by ErebusAres** [Sepichat/FoundryVTT-GiveItem#14]
Giving the item removes the item from your inventory, but it does not give the item to the player you give it to.
also, the DM gets a message and can take the item as well, causing you to lose 2 instead of 1 of the item(s)

**Comment by Nedrapter** [comment]
I loved that module. Would much like to see it updated.

**Comment by Sepichat** [comment]
Hello guys,

Someone provided a fix for that compatibility issue that I just merged.
You can check #13
