### ISSUE TITLE
Add trade for currencies

### ISSUE THREAD

**Issue by DarKDinDoN** [Sepichat/FoundryVTT-GiveItem#2]
Hello,

Would be great if we can trade the gold as well 😃 

Also, there is great module to change the currency names here: https://github.com/ktrieun/FVTT-5e-custom-currency
Would be great if this module is compatible

**Comment by Sepichat** [comment]
That is something I already had in mind but I didn't have the time to implement it yet. 
It will probably part of the next release.

**Comment by Sepichat** [comment]
Implemented in release 1.3.0 (4b8af6dca0c71e156434a0ab16d586e1658fbb04)
