### ISSUE TITLE
Compatibility with tidy5e-sheet

### ISSUE THREAD

**Issue by rthill91** [Sepichat/FoundryVTT-GiveItem#24]
I'd love to use this module, but I don't think I can give up tidy5e-sheet. Would it be incredibly difficult to add support for it?

Out of the box it looks like currency exchange works, but the buttons for transferring items seems to be lost.

**Comment by Sepichat** [comment]
Hey @rthill91 ,
I am currently using it with Tidy5e. The buttons are there but "hidden" under the right click command your item.
Let me know if you have any kind of issue with this, but last time I tried it was still working fine.

**Comment by rthill91** [comment]
@Sepichat,

You're absolutely right, I just completely missed it. I saw it in the default sheet and not in tidy and didn't think to check for an overflow menu. Thanks for the help!
