### ISSUE TITLE
Wrong version, foundry updates this module every time

### ISSUE THREAD

**Issue by diwako** [Sepichat/FoundryVTT-GiveItem#26]
It looks like foundry checks the new version, updates it but it still says it is the old version afterwards

![image](https://user-images.githubusercontent.com/8259498/131247295-66d7e1d9-6e67-4e6c-be81-4d36c9e57650.png)

Each update check this happens.

Deleting and reinstalling the module does not help, the install window shows the correct version however
![image](https://user-images.githubusercontent.com/8259498/131247356-654b4691-4e64-4d15-b4cb-4e38c5a1d370.png)

**Comment by Sepichat** [comment]
Hello @diwako 
Thanks for the notice. 
I will try to have a look asap at this issue. I must have put a wrong number somewhere in the configuration.
I'm taking a few days off this week so it will probably not be before next week, unless I get lucky and find some time before then.

**Comment by dirusulixes** [comment]
hi, I think the issue is that you manifest for 1.10.1 actually points to the 1.10.0 release download link 
https://github.com/Sepichat/FoundryVTT-GiveItem/blob/a5ccb4ac6b4ebd82a501a42ac21f4704b261428c/module.json#L19

**Comment by monkey-bars** [comment]
This is still happening.

**Comment by crogonint** [comment]
Still happening in 0.8.9

..I think I'll just grab that link above and manually grab it myself to stop the behavior. ;)

**Comment by Sepichat** [comment]
Fixed by #33
