### ISSUE TITLE
Error when trying to give an item

### ISSUE THREAD

**Issue by DarKDinDoN** [Sepichat/FoundryVTT-GiveItem#3]
When trying to give an item as a player, I get this error message:
![image](https://user-images.githubusercontent.com/1687854/104927708-09dd3c80-59a2-11eb-975b-438ccb078974.png)

**Comment by Sepichat** [comment]
Thanks for the issue @DarKDinDoN .

Is the user Belgrim the owner of the actor ?
Could you provide me with a basic foundry configuration so I can try and reproduce the issue?

- The Users created and their permissions related to actors
- A scenario step by step would be welcome

**Comment by Sepichat** [comment]
OK I think I found the issue.
It's when Foundry check for the which user actually updates which player.
If the player being given the items is not owned by the player doing the update, the transaction is being rejected.
I'm investigating how to solve the issue

**Comment by cs96and** [comment]
Also, the item is removed from the original player's sheet, meaning that it is now lost (probably scattered onto the ethereal plane :-) )

**Comment by cs96and** [comment]
It might be taking a look at how DAE works.  Players can apply affects to targets, but I think the GM has to be logged in for it to work.  It must route everything through the GM somehow.

**Comment by MaxtorDD** [comment]
I have the same problem with an build-house system in which I want to automate hits points.
I have been confirmed to use sockets to emit an event with the required data and check in the listener if the current user is the first active GM, then go through with the entity update.
For lack of time, I gave up for the moment. But there's en other example in module "Player token permission extended".

**Comment by fredrlw** [comment]
Hi, I have the same issue aswell but I just change actor sheets, but I don't know if it worked before switching sheets... 
But can it have something to do with not using the default player actor sheet?
Iam on my phone right now so cant double check while writing this. but I did read a line in the code " dnde5.characterActorSheet" or something. 
Could that be an issue when not using the default sheet?

**Comment by Sepichat** [comment]
Sorry guys, I have been quite busy until now.
I investigated the issue and I will have a look at how to solve this issue this weekend. It seems it's related to the human player (not ingame actor) missing the access to the other actor who the item is gifted to.
Foundry has a built in security system to prevent a different player from updating an actor who doesn't belong to him.
The way to avoid this issue is to actually forward the update request to the player controlling the actor who is gifted the item. Unless I find another solution meanwhile I will implement it that way for the moment.

**Comment by jseaz73** [comment]
Any update on this issue?  I am the DM for a group of 11 yr olds ... and they are a handful :-)

**Comment by MaxtorDD** [comment]
Hello,
Have you give up this module ? :/

**Comment by jseaz73** [comment]
> Sorry guys, I have been quite busy until now.
> I investigated the issue and I will have a look at how to solve this issue this weekend. It seems it's related to the human player (not ingame actor) missing the access to the other actor who the item is gifted to.
> Foundry has a built in security system to prevent a different player from updating an actor who doesn't belong to him.
> The way to avoid this issue is to actually forward the update request to the player controlling the actor who is gifted the item. Unless I find another solution meanwhile I will implement it that way for the moment.

You should be able to do this thru the GM actor.

**Comment by Sepichat** [comment]
Hello Guys,

Sorry if I let you down for so long, but i was finally able to fix the issue.
Now when an actor send something to another actor, the target will receive a small popup where he needs to accept or decline the offer, in which cases the inventories will be updated properly.
Please update to the version 1.3.1 and let me know if you find any other issue
