### ISSUE TITLE
Give Item button missing from inventory for unidentified items

### ISSUE THREAD

**Issue by bluedreamer** [Sepichat/FoundryVTT-GiveItem#32]
Hi, I am a player in a PF2 game and I have 3 unidentified items in my inventory but they are missing the give item button. I have attached a screen shot.

Foundry: 0.8.9
PF2: 2.17.0.8553
Give Item: 1.10.0
![image](https://user-images.githubusercontent.com/753610/138619962-b6278cc9-05e4-4ef9-a920-608157c4abd2.png)

Let me know if I can provide any more information

**Comment by Sepichat** [comment]
Ohhh, I never noticed this. It should be an easy fix.
I'm adding the button after the edit one, which doesn't exist for unidentified items.

**Comment by Sepichat** [comment]
Actually I just realized that it's fixed following migration to foundry v11 with the v2.0.0 #48
