### ISSUE TITLE
[FEATURE] Only show selected characters

### ISSUE THREAD

**Issue by 9ryex5** [Sepichat/FoundryVTT-GiveItem#4]
On trading options give the option to only show players' "Main Characters", the one selected here:

![image](https://user-images.githubusercontent.com/43207603/104949644-3485c000-59b7-11eb-8330-3264ee215673.png)

Currently there is an option to trade with any Owned character. Usually players will own creatures to summon, tokens for spells, friendly NPCs, etc. and the list of actors to trade with can become too long.

**Comment by Handyfon** [comment]
100% this

**Comment by Sepichat** [comment]
I will start having a loot at this issue this weekend.
How would you describe a "Main Characters"? 
When creating a familiar or any creature to summon, it's created as a PC, no?
I'm trying to find a way to discriminate between the different actors. It's quite easy to remove the NPC, but if the creatures and tokens are created as PC it might be a lot more complicated to filter them out.
Please give me a bit more details about some scenario that I could test like a small list of PC/NCP/Creatures that you create in your campaign.

Thanks

**Comment by Handyfon** [comment]
Awesome.
You can find selected characters on each of the players.
For example game.users.players[0].character
You can just loop trough the players array.

**Comment by Handyfon** [comment]
That is an easy way to access the characters
![image](https://user-images.githubusercontent.com/28778881/112672115-6017a180-8e63-11eb-93de-c5693f469291.png)

**Comment by Sepichat** [comment]
Thanks for the info :)
I will update the filter to show only these characters in the list then

**Comment by Sepichat** [comment]
This should be fixed with version 1.5.0 :)
