### ISSUE TITLE
V10 compability

### ISSUE THREAD

**Issue by Kevin1710** [Sepichat/FoundryVTT-GiveItem#40]
Hello!
I just want to ask if there is any chance that this module is updated to Foundry V10.

Kind regards
Kevin!

**Comment by jstebenne** [comment]
I would also like an update for V10

Currently, it is possible to initial a trade, but when the receiving player tries to accept, this error appears:

![image](https://user-images.githubusercontent.com/1571895/193172421-6f7249c8-a26c-4a22-bb7d-455c4cce227b.png)

And this appears in the console:

```javascript
TypeError: Cannot read properties of undefined (reading 'quantity')
    at receiveItem (trading.js:108:35)
    at tradeConfirmed (trading.js:192:9)
    at Object.callback (trading.js:9:33)
    at Dialog.submit (foundry.js:55745:35)
    at Dialog._onClickButton (foundry.js:55674:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

**Comment by LonePaladin** [comment]
I can second jstebenne's response, I've been getting the same error since updating to V10.

**Comment by Txus5012** [comment]
I made this v10 compatibility update. Needs more testing, though.
https://github.com/Txus5012/FoundryVTT-GiveItem

Also includes [this PR](https://github.com/Sepichat/FoundryVTT-GiveItem/pull/23).

**Comment by weepingminotaur** [comment]
> https://github.com/Txus5012/FoundryVTT-GiveItem

Tried to install, returned a manifest error.

**Comment by weepingminotaur** [comment]
Would love for this module to become v10 compatible!

**Comment by Txus5012** [comment]
It was meant to be manually downloaded. I created a proper release for it and a [discussion thread](https://github.com/Txus5012/FoundryVTT-GiveItem/discussions/4).

**Comment by Sepichat** [comment]
Hey I know that it's long overdue but I finally got some time to update the module.
Thanks for the update @Txus5012  , I based the update on your changes.

**Comment by Sepichat** [comment]
Feel free to update to version 1.12.1 (or latest)

**Comment by Sepichat** [comment]
#42 #43
