### ISSUE TITLE
Party member not showing in trade list

### ISSUE THREAD

**Issue by AkmenosDuFrey** [Sepichat/FoundryVTT-GiveItem#45]
Just downloaded the module and was trying it out tonight with my group because we're switching to foundry from roll20. They were playing with the mod trying to figure out how it works and one member of the party just didn't show up in the list to be able to be traded with. I did activate the mod in the configure settings tab.
I created an actor to drop in to share a torch, and he still wasn't in my list as the GM.
I'm using the 5e world, he's a Harengon Samurai if that matters.

**Comment by Sepichat** [comment]
Hey!

Was the player ever linked to the actor?
As far as I remember the actor must have an owner which usually is set when the player connects for the first time and "accepts" the actor.
You should be able to do so for him (just login as that player and accept the actor) and from that point on he should appear in the list.

**Comment by AkmenosDuFrey** [comment]
Hey back!
That was exactly it, I logged into the affected player and he hadn't accepted control of his token.
Accepted and he was in the lists.
Thank you!!

**Comment by Sepichat** [comment]
Happy to hear that it worked!
Enjoy your games
