### ISSUE TITLE
In PF2e System 5.11.5 the buttons no longer show up

### ISSUE THREAD

**Issue by maplealmond** [Sepichat/FoundryVTT-GiveItem#47]
Tested with a pristine world of PF2e with no only Give Item enabled.  Buttons no longer appear, when they did previously.

**Comment by Sepichat** [comment]
The afore mentioned version is [v2.0.0](https://github.com/Sepichat/FoundryVTT-GiveItem/releases/tag/v2.0.0)

**Comment by maplealmond** [comment]
After installing it works.  Dropping a note only to say thank you, my alchemist player rather adores this one.
