### ISSUE TITLE
Editing HP and Exp on character sheet and pressing enter pops up Give Currency pop-up (PF2E, possibly others)

### ISSUE THREAD

**Issue by SumoCow** [Sepichat/FoundryVTT-GiveItem#50]
As title says. Steps to reproduce: 
Open Character sheet
Click into HP, Shield HP or EXP fields to edit them 
Press Enter (return or 10-key enter) even with or without actually modifying the value.

![image](https://github.com/Sepichat/FoundryVTT-GiveItem/assets/159641183/f61f7ced-3199-4b23-9277-e6c4077dc6ba)

This shows up with or without the "activate give item" checkbox marked as active.

**Comment by Sepichat** [comment]
The problem was with the button used to send some currency to other players, I forgot to add a type, and it defaulted to the wrong type.
It should be fixed with #51 and release v2.2.1
